import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@/styles/globals.css';
import localFont from 'next/font/local';
import { cn } from '@/utils/cn';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const giorgio = localFont({
  src: '../assets/fonts/giorgio-regular.woff2',
  weight: '400',
  variable: '--font-title',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-body',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="custom-scrollbar scroll-smooth motion-reduce:scroll-auto"
    >
      <body
        className={cn(
          'typography-body flex min-h-dvh flex-col bg-black text-anti-flash-white antialiased',
          giorgio.variable,
          montserrat.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
